export * from './Welcome';
export * from './About';
export * from './Features';
export * from './Images';
export * from './OutStory';
export * from './OutStoryCenter';
export * from './Reviews';
export * from './Slogan';
export * from './Social';
